### ISSUE TITLE
modules in the project

### ISSUE THREAD

**Issue by RamuMakkena** [ballardingram/group-project2-codEZ#2]
1. Front end data representation  (components involved are to read and post data in a web page)
2. CSS modifications for front end (Component is to provide styling for the pages & individual blocks on the page)
3. Server.js setup with API routes (Setting up routes for both frontend to call and backend code to call for data)
4. Sequelize & mysql setup with data design (designing the data models & setting up a database with environment variables)
5. workflow implementations  (login, posts, account creations etc)

Front end <=> server.js <=> business logic (controller) <=> sequelize <=> database

**Comment by RamuMakkena** [comment]
Setting up Heroku environment with mysql

**Comment by RamuMakkena** [comment]
Ramu: Heroku Setup, Express js api routes & signup & login with passport
Ballard: Database models & sequelize

**Comment by RamuMakkena** [comment]
Shuan: Handlebars for html templating
Cassandra : Front end implementation.

**Comment by ballardingram** [comment]
ROUTES - Working on them.
User Routes - done

**Comment by ballardingram** [comment]
tips route - done
